INSERT INTO `questionBank` VALUES (1, 'C++', '0', 'C', '一加一等于加', '0', '1', '2', '3');
INSERT INTO `questionBank` VALUES (2, '计算机网络技术', '1', '西瓜、橙子', '你喜欢什么东西？', '西瓜', '橙子', '橘子', '红枣');
INSERT INTO `questionBank` VALUES (3, 'C语言', '2', '断肠人在天涯', '夕阳西下，（）', NULL, NULL, NULL, NULL);
INSERT INTO `questionBank` VALUES (4, '数学', '3', '1+1=2', '一加一等于几？', NULL, NULL, NULL, NULL);
INSERT INTO `questionBank` VALUES (5, '数学', '0', 'D', '5+9=()', '11', '12', '13', '14');
INSERT INTO `questionBank` VALUES (6, '数学', '0', 'B', '1+6=()', '6', '7', '8', '9');
INSERT INTO `questionBank` VALUES (7, 'C语言', '0', 'B', '1+6=（）', '6', '7', '8', '9');
INSERT INTO `questionBank` VALUES (8, 'C语言', '0', 'A', '（）是构成C语言程序的基本单位。', '函数', '过程', '子程序', '子例程');
INSERT INTO `questionBank` VALUES (9, 'C语言', '0', 'C', 'C语言程序从（）开始执行。', '程序中第一条可执行语句', '程序中第一个函数', '程序中main函数', '包含文件中的第一个函数');
INSERT INTO `questionBank` VALUES (10, 'C语言', '0', 'C', '下列正确的标识符是()', '-a1', 'a[i]', 'a2_i', 'int t');
INSERT INTO `questionBank` VALUES (11, 'C语言', '2', '1', '若a=6，b=4，c=3，则表达式  a&&b||b-c的值是()', NULL, NULL, NULL, NULL);
INSERT INTO `questionBank` VALUES (12, 'C语言', '3', '略', '编程打印九九乘法表', NULL, NULL, NULL, NULL);
INSERT INTO `questionBank` VALUES (13, '数学', '2', '12根', '桌子上原来有12支点燃的蜡烛，先被风吹灭了3根，不久又一阵风吹灭了2根，最后桌子上还剩几根蜡烛呢？', NULL, NULL, NULL, NULL);
INSERT INTO `questionBank` VALUES (14, '数学', '2', '50', '狐狸用50元的假钞买走了老山羊店里一件45元的皮衣，老山羊还找给狐狸5元钱，那么你知道老山羊损失了多少元钱吗？', NULL, NULL, NULL, NULL);
INSERT INTO `questionBank` VALUES (15, '数学', '2', '12个', '24人排成一排，一、二报数，报二的人向前走两步，问：原地不动的人有几个？', NULL, NULL, NULL, NULL);
INSERT INTO `questionBank` VALUES (16, '数学', '3', '18面', '在一条长40米的马路两旁插彩旗，每隔5米插一面，一共要插多少面彩旗？', NULL, NULL, NULL, NULL);
INSERT INTO `questionBank` VALUES (17, '数学', '3', '3个', '有两盘苹果，甲盘有7个，如果从甲盘中拿出2个放入乙盘，两盘的苹果就同样多，乙盘原来有多少个？', NULL, NULL, NULL, NULL);
INSERT INTO `questionBank` VALUES (21, '数学', '0', 'B', '63+7=（）', '69', '70', '71', '72');
INSERT INTO `questionBank` VALUES (22, '数学', '1', 'AC', '你喜欢什么颜色？', '红色', '黄色', '绿色', '蓝色');
INSERT INTO `questionBank` VALUES (23, '语文', '2', '寂寞梧桐深院锁清秋', '无言独上西楼，月如钩，（）', '', '', '', '');
INSERT INTO `questionBank` VALUES (24, '数学', '3', '3+2=5（个）', '树上三个苹果，树下两个苹果，一共多少个苹果？', '', '', '', '');
INSERT INTO `questionBank` VALUES (25, '数学', '0', 'A', 'ff', '111', '11', '', '');
INSERT INTO `questionBank` VALUES (26, '数学', '1', 'BD', '那个你最喜欢', '西瓜', '苹果', '梨', '香蕉');
